[package]
name = "ktangle"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
smithay-client-toolkit = "0.19.2"
wayland-client = "0.31.8"
wayland-protocols = "0.32.6"
wayland-scanner = "0.31.6"
